### Neshyba 2023


# Kronecker Products

## Introduction

In this exercise, one of our goals is to show how to construct matrices representing kinetic energy in three dimensions, extending the pattern we followed in two dimensions, using the Kronecker product. We'll also be taking a look at some of the analytical properties of those matrices, so that you'll become a little more comfortable about using these tools.

## Matrix representation of $\nabla^2$ in 2d
Previously, we considered the kinetic energy operators of a particle moving in each of two Cartesian dimensions, 

$$
KE = {-\hbar^2 \over 2 m} \nabla^2  \ \ \ \ (1)
$$

where $\nabla^2$ is the sum of second derivatives, ${\partial^2 \over \partial x^2} + {\partial^2 \over \partial y^2}$. We can think about matrices corresponding to $\nabla^2$ using formulas like

    del2x = (-2.0*np.diag(np.ones(nx))+np.diag(np.ones(nx-1),1)+np.diag(np.ones(nx-1),-1)) /dx**2

and similarly for the y-direction. Then, with the help of identity matrices like 

    Ix = np.diag(np.ones(nx))

we can construct the matrix representation of $\nabla^2$

    del2_2d = np.kron(del2x,Iy) + np.kron(Ix,del2y)
    
where np.kron is numpy's Kronecker delta function.

## Matrix representation of $\nabla^2$ in 3d
Formally, this is is constructed in an analogous way, e.g.,  

    del2_3d = PL.kron3(del2x,Iy,Iz) + PL.kron3(Ix,del2y,Iz) + PL.kron3(Ix,Iy,del2z)
    
where PL.kron3 is a three-dimensional generalization of Numpy's kron2 function, supplied in our PchemLibrary. 

## Loops
In order to compare the eigenvalues of a Kronecker product matrix to the eigenvalues of the lower-dimensional matrices that went into making it, it will be useful to set up some loops. You'll see how those work in the 2d example below; the 3d case is a straightforward extension.

## Learning goals
The main learning goals of this exercise are:
1. I can predict the size of Kronecker product matrices that will arise from matrices of lower dimension.
1. I can construct those Kronecker product matrices, and can identify whether it is diagonal, tridiagonal, etc.
1. I can predict the eigenvalues of Kronecker product matrix based on the eigenvalues of the lower-dimensional matrices that went into making it.
1. I can set up Python loops.

In [9]:
import numpy as np
import scipy.linalg as spla
import plotly.graph_objects as go
import PchemLibrary as PL
%matplotlib notebook

### Constructing identity matrices
Below, we construct identity matrices when $n_x=3$ and $n_y=4$. To simplify things, we're going to assume discretization intervals $dx=dy=1$.

In [10]:
# Decide on the discretization in the x- and y-directions
nx = 3; dx = 1
ny = 4; dy = 1

# Make the identity matrix in the x-direction
Ix = np.diag(np.ones(nx))
print(Ix)

# Same for y (but using ny)
### BEGIN SOLUTION
Iy = np.diag(np.ones(ny))
print(Iy)
### END SOLUTION

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### Pause for analysis
Why do you suppose these are called diagonal matrices? What's special about these particular diagonal matrices (where all the non-zero elements are equal to 1)? (see, e.g., https://en.wikipedia.org/wiki/Diagonal_matrix.)

### BEGIN SOLUTION

Diagonal matrices are matrices in which only diagonal elements are non-zero. If all the non-zero elements are equal to 1, it's the identity matrix.

### END SOLUTION

### Matrix representations of  ${\partial^2 \over \partial x^2}$ and ${\partial^2 \over \partial y^2}$.

In [11]:
# Get the second-derivative matrix in the x-direction
del2x = (-2.0*np.diag(np.ones(nx))+np.diag(np.ones(nx-1),1)+np.diag(np.ones(nx-1),-1)) /dx**2
print('del2x:')
print(np.shape(del2x))
print(del2x)

# Get the second-derivative matrix in the y-direction
### BEGIN SOLUTION
del2y = (-2.0*np.diag(np.ones(ny))+np.diag(np.ones(ny-1),1)+np.diag(np.ones(ny-1),-1)) /dy**2
print('del2y:')
print(np.shape(del2y))
print(del2y)
### END SOLUTION

del2x:
(3, 3)
[[-2.  1.  0.]
 [ 1. -2.  1.]
 [ 0.  1. -2.]]
del2y:
(4, 4)
[[-2.  1.  0.  0.]
 [ 1. -2.  1.  0.]
 [ 0.  1. -2.  1.]
 [ 0.  0.  1. -2.]]


### Pause for analysis
Why do you suppose these matrices are called "tridiagonal"? (See, e.g., https://en.wikipedia.org/wiki/Tridiagonal_matrix.)

### BEGIN SOLUTION
Because only the diagonal, and one above and one below, have non-zero entries.
### END SOLUTION

### Building the matrix representation of $\nabla^2$ in 2d
In the cell below, we construct a matrix representation of $\nabla^2$ in 2d.

In [12]:
# Constructing the del2 matrix from the x- and y- second derivative matrices
del2_2d = np.kron(del2x,Iy) + np.kron(Ix,del2y)
print(np.shape(del2_2d))
print(del2_2d)

# This is an attempt at visualizing it
fig = go.Figure(data=go.Surface(z=del2_2d))
fig.update_layout(scene = dict(
                    xaxis_title="row of del2_2d",
                    yaxis_title="column of del2_2d",
                    zaxis_title='del2_2d'))

(12, 12)
[[-4.  1.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 1. -4.  1.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  1. -4.  1.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  1. -4.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 1.  0.  0.  0. -4.  1.  0.  0.  1.  0.  0.  0.]
 [ 0.  1.  0.  0.  1. -4.  1.  0.  0.  1.  0.  0.]
 [ 0.  0.  1.  0.  0.  1. -4.  1.  0.  0.  1.  0.]
 [ 0.  0.  0.  1.  0.  0.  1. -4.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  1.  0.  0.  0. -4.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  1. -4.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  0.  1. -4.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  1. -4.]]


### Pause for analysis
Two questions here:
1. The matrix representing $\nabla^2$ is not tridiagonal, but what is it? Tetradiagonal? Pentadiagonal? Hexadiagonal? 
1. Supposedly, the matrix representing $\nabla^2$ is square-shaped, with $N=nx \times ny$ rows and columns. Did that work out here? 

### BEGIN SOLUTION
1. It has nonzero elements in row/column 5, so maybe hexa?
1. Yes, since N = 3 * 4 = 12  

### END SOLUTION

### A cool thing about the Kronecker product
Here's a cool thing: eigenvalues of $\nabla^2$ are *supposed* to equal combinations of eigenvalues of ${\partial^2 \over \partial x^2}$ and ${\partial^2 \over \partial y^2}$! You're tasked with verifying that assertion in the cell below.

To make this comparison, we're constructing some Python loops. The first one is actually a *nested loop* because it is looping over two variables. The second one, which you're prompted to make, is a little easier to construct because there's only one variable to loop over. If you named your eigenvalue variable Epsi_2d, this loop could look something like

    for i in range(nx*ny):
        print(Epsi_2d[i])


In [13]:
# Diagonalizing the second derivative matrices and and reporting the sum of their eigenvalues
Epsix,psix = spla.eigh(del2x)
Epsiy,psiy = spla.eigh(del2y)
print('\n Sums of eigenvalues of del2x and del2y:')
for ix in range(nx):
    for iy in range(ny):
        print(Epsix[ix]+Epsiy[iy])

# Diagonalizing del2_2d, and reporting its eigenvalues
### BEGIN SOLUTION
Epsi_2d,psi_2d = spla.eigh(del2_2d)
print('\n Products of eigenvalues of del2_2d:')
for i in range(nx*ny):
    print(Epsi_2d[i])
### END SOLUTION


 Sums of eigenvalues of del2x and del2y:
-7.032247551122983
-6.032247551122987
-4.7961795736231965
-3.7961795736231982
-5.618033988749888
-4.618033988749893
-3.3819660112501024
-2.3819660112501038
-4.203820426376795
-3.203820426376799
-1.9677524488770086
-0.9677524488770102

 Products of eigenvalues of del2_2d:
-7.032247551122994
-6.032247551122989
-5.618033988749894
-4.796179573623201
-4.618033988749893
-4.203820426376795
-3.796179573623196
-3.3819660112501033
-3.2038204263768018
-2.3819660112501024
-1.9677524488770082
-0.9677524488770097


### Pause for analysis
Do they match?

### BEGIN SOLUTION

Yeah!

### END SOLUTION

### Predicting the size of the matrix representation of $\nabla^2$ in 3d
Similarly to the 2d case, the matrix representation of $\nabla^2$ in three dimensions should be an $N \times N$ (square) matrix with $N=nx \times ny \times nz$. Predict $N$ for the $\nabla^2$ matrix when $n_x=3$, $n_y=4$, and $n_z=5$.

In [14]:
### BEGIN SOLUTION
nz = 5
N = nx*ny*nz
print(N)
### END SOLUTION

60


### Building a matrix representation of $\nabla^2$ in 3d
In the cell below, compute a matrix representation of $\nabla^2$ when $n_x=3$, $n_y=4$, and $n_z=5$. Some pointers:

- Just as we set $dx=dy=1$, set $dz=1$ here too.
- You will have to build ${\partial^2 \over \partial z^2}$, but you don't have to rebuild matrix representations of ${\partial^2 \over \partial x^2}$ and ${\partial^2 \over \partial y^2}$, since they're already in your workspace (as variables del2x and del2y). 
- It'll be handy to use the PchemLibrary function kron3 for when you go to combine these into one big Kronecker matrix (see the Introduction).

You should also do some graphics to visualize it, something along the lines of the following (assuming you've named your matrix del2_3d):

    fig = go.Figure(data=go.Surface(z=del2_3d))
    fig.update_layout(scene = dict(
                    xaxis_title="row of del2_3d",
                    yaxis_title="column of del2_3d",
                    zaxis_title='del2_3d'))

In [15]:
### BEGIN SOLUTION

# Discretization
nz = 5
dz = 1

# Get the 1-d identity matrix in the z-direction
Iz = np.diag(np.ones(nz))
print(Iz)

# Construct the del^2 matrix in the z-direction
del2z = (-2.0*np.diag(np.ones(nz))+np.diag(np.ones(nz-1),1)+np.diag(np.ones(nz-1),-1))/dz**2
print(del2z)

# Construct the full del^2 matrix as a Kronecker sum
del2_3d = PL.kron3(del2x,Iy,Iz) + PL.kron3(Ix,del2y,Iz) + PL.kron3(Ix,Iy,del2z)
print(np.shape(del2_3d))
for i in range(nx*ny*nz):
    print(del2_3d[i,:])

# This is an attempt at visualizing it
fig = go.Figure(data=go.Surface(z=del2_3d))
fig.update_layout(scene = dict(
                    xaxis_title="row of del2_3d",
                    yaxis_title="column of del2_3d",
                    zaxis_title='del2_3d'))
### END SOLUTION

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[-2.  1.  0.  0.  0.]
 [ 1. -2.  1.  0.  0.]
 [ 0.  1. -2.  1.  0.]
 [ 0.  0.  1. -2.  1.]
 [ 0.  0.  0.  1. -2.]]
(60, 60)
[-6.  1.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.]
[ 1. -6.  1.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.]
[ 0.  1. -6.  1.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.]
[ 0.  0.  1. -6.  1.  0.  0.  0.  1.  0.  0.  0. 

### Pause for analysis
As you can see, the matrix representation of $\nabla^2$ in 3d is much bigger now. Does it have the size you expected?

### BEGIN SOLUTION
Yes, because $3 \times 4 \times 5=60$. Also, the non-zero off-diagonals are one farther "out" compared to the 2d case.

### END SOLUTION

### A cool thing about the Kronecker product of $\nabla^2$ (in 3d)
In the cell below, the idea is to verify that eigenvalues of the $\nabla^2$ matrix you just got are equal to sums of eigenvalues of ${\partial^2 \over \partial x^2}$, ${\partial^2 \over \partial y^2}$, and ${\partial^2 \over \partial z^2}$.

In [16]:
# Diagonalize del2z
### BEGIN SOLUTION
Epsiz,psiz = spla.eigh(del2z)
### END SOLUTION

# Report sums of eigenvalues of del2x, del2y, and del2z
### BEGIN SOLUTION
print('\n Sums of eigenvalues of del2x, del2y, and del2z:')
for ix in range(nx):
    for iy in range(ny):
        for iz in range(nz):
            print(Epsix[ix]+Epsiy[iy]+Epsiz[iz])
### END SOLUTION

# Diagonalizing del2_3d, and reporting its eigenvalues
### BEGIN SOLUTION
Epsi3,psi3 = spla.eigh(del2_3d)
print('\n Products of eigenvalues of del2_3d:')
for i in range(nx*ny*nz):
    print(Epsi3[i])
### END SOLUTION


 Sums of eigenvalues of del2x, del2y, and del2z:
-10.764298358691855
-10.03224755112298
-9.032247551122982
-8.032247551122982
-7.300196743554105
-9.76429835869186
-9.032247551122984
-8.032247551122985
-7.032247551122986
-6.3001967435541095
-8.528230381192069
-7.796179573623194
-6.796179573623195
-5.796179573623196
-5.064128766054319
-7.5282303811920706
-6.796179573623196
-5.7961795736231965
-4.796179573623197
-4.064128766054321
-9.350084796318761
-8.618033988749884
-7.618033988749886
-6.618033988749887
-5.88598318118101
-8.350084796318766
-7.61803398874989
-6.618033988749891
-5.618033988749892
-4.8859831811810155
-7.114016818818975
-6.3819660112501
-5.381966011250101
-4.3819660112501015
-3.6499152036812252
-6.1140168188189765
-5.381966011250101
-4.381966011250102
-3.3819660112501024
-2.6499152036812266
-7.935871233945667
-7.203820426376792
-6.203820426376793
-5.203820426376794
-4.471769618807917
-6.935871233945672
-6.2038204263767955
-5.203820426376797
-4.203820426376798
-3.4717696188

### Refreshing and saving your code
1. Use the dropdown menu Kernel/Restart
2. Use the dropdown menu Cell/Run All Above
3. Under the "File" dropdown menu item in the upper left is a disk icon. Press it now to save your work (you can, do this at any time as you're working on an assignment, actually).

### Validating
This step will help ensure that you didn't miss something (although it's not a guarantee). Find the "Validate" button and press it. If there are any errors or warnings, fix them.

### Finishing up
Assuming all this has gone smoothly, carry out three more steps (but read this carefully before starting):
1. Close this notebook using the "File/Close and Halt" dropdown menu
1. Using the Assignments tab, submit this notebook
1. Press the Logout tab of the Home Page